### ISSUE TITLE
Add option to access certain context menu options with keyboard shortcut.

### ISSUE THREAD

**Issue by pslobo** [careteditor/issues#313]
I'd like to be able to trigger certain actions that are available in the context menu via a keyboard shortcut.

You could add an extra section the keyboard-shortcuts.md like:

```yaml
## Context Actions
```yaml
check item: cmd  D
open link: shift cmd O
....
```

The context menu is great, but this could save some time and keystrokes for things that I do often.
